// Generated by build/expected.mjs from source/figma-variables.json.
// Independent of build.mjs and dist/tokens.css: walks the Figma export directly.
// Do not hand-edit. Re-run build/expected.mjs to refresh.
window.DS_EXPECTED = {
  "colorCombos": [
    {
      "theme": "light",
      "contrast": "standard",
      "temperature": "cool",
      "label": "Light / Standard / Cool"
    },
    {
      "theme": "light",
      "contrast": "standard",
      "temperature": "warm",
      "label": "Light / Standard / Warm"
    },
    {
      "theme": "light",
      "contrast": "medium",
      "temperature": "cool",
      "label": "Light / Medium / Cool"
    },
    {
      "theme": "light",
      "contrast": "medium",
      "temperature": "warm",
      "label": "Light / Medium / Warm"
    },
    {
      "theme": "light",
      "contrast": "high",
      "temperature": "cool",
      "label": "Light / High / Cool"
    },
    {
      "theme": "light",
      "contrast": "high",
      "temperature": "warm",
      "label": "Light / High / Warm"
    },
    {
      "theme": "dark",
      "contrast": "standard",
      "temperature": "cool",
      "label": "Dark / Standard / Cool"
    },
    {
      "theme": "dark",
      "contrast": "standard",
      "temperature": "warm",
      "label": "Dark / Standard / Warm"
    },
    {
      "theme": "dark",
      "contrast": "medium",
      "temperature": "cool",
      "label": "Dark / Medium / Cool"
    },
    {
      "theme": "dark",
      "contrast": "medium",
      "temperature": "warm",
      "label": "Dark / Medium / Warm"
    },
    {
      "theme": "dark",
      "contrast": "high",
      "temperature": "cool",
      "label": "Dark / High / Cool"
    },
    {
      "theme": "dark",
      "contrast": "high",
      "temperature": "warm",
      "label": "Dark / High / Warm"
    }
  ],
  "sizeCombos": [
    {
      "screen": "mobile",
      "scale": "1",
      "label": "Mobile / 1X"
    },
    {
      "screen": "mobile",
      "scale": "1.2",
      "label": "Mobile / 1.2X"
    },
    {
      "screen": "mobile",
      "scale": "1.4",
      "label": "Mobile / 1.4X"
    },
    {
      "screen": "mobile",
      "scale": "1.6",
      "label": "Mobile / 1.6X"
    },
    {
      "screen": "mobile",
      "scale": "1.8",
      "label": "Mobile / 1.8X"
    },
    {
      "screen": "mobile",
      "scale": "2",
      "label": "Mobile / 2X"
    },
    {
      "screen": "tablet",
      "scale": "1",
      "label": "Tablet / 1X"
    },
    {
      "screen": "tablet",
      "scale": "1.2",
      "label": "Tablet / 1.2X"
    },
    {
      "screen": "tablet",
      "scale": "1.4",
      "label": "Tablet / 1.4X"
    },
    {
      "screen": "tablet",
      "scale": "1.6",
      "label": "Tablet / 1.6X"
    },
    {
      "screen": "tablet",
      "scale": "1.8",
      "label": "Tablet / 1.8X"
    },
    {
      "screen": "tablet",
      "scale": "2",
      "label": "Tablet / 2X"
    },
    {
      "screen": "desktop",
      "scale": "1",
      "label": "Desktop / 1X"
    },
    {
      "screen": "desktop",
      "scale": "1.2",
      "label": "Desktop / 1.2X"
    },
    {
      "screen": "desktop",
      "scale": "1.4",
      "label": "Desktop / 1.4X"
    },
    {
      "screen": "desktop",
      "scale": "1.6",
      "label": "Desktop / 1.6X"
    },
    {
      "screen": "desktop",
      "scale": "1.8",
      "label": "Desktop / 1.8X"
    },
    {
      "screen": "desktop",
      "scale": "2",
      "label": "Desktop / 2X"
    }
  ],
  "colorTokens": [
    {
      "name": "--ds-color-background-card",
      "kind": "color",
      "values": [
        "#f8fafc",
        "#fbf9f7",
        "#f8fafc",
        "#fbf9f7",
        "#f8fafc",
        "#fbf9f7",
        "#191d2c",
        "#231d19",
        "#191d2c",
        "#231d19",
        "#080c17",
        "#100c09"
      ]
    },
    {
      "name": "--ds-color-information-primary",
      "kind": "color",
      "values": [
        "#222a3b",
        "#322821",
        "#191d2c",
        "#231d19",
        "#080c17",
        "#100c09",
        "#e6e8ea",
        "#ebe7e4",
        "#f8fafc",
        "#fbf9f7",
        "#f8fafc",
        "#fbf9f7"
      ]
    },
    {
      "name": "--ds-color-border-focus",
      "kind": "color",
      "values": [
        "#0053d0",
        "#3b672d",
        "#003db4",
        "#2d5124",
        "#002c87",
        "#1f3b1a",
        "#70a3d9",
        "#7fab70",
        "#a1bddf",
        "#a3c397",
        "#cad9ed",
        "#ccddc4"
      ]
    },
    {
      "name": "--ds-color-button-primary-fill-fill",
      "kind": "color",
      "values": [
        "#0053d0",
        "#3b672d",
        "#003db4",
        "#2d5124",
        "#002c87",
        "#1f3b1a",
        "#70a3d9",
        "#7fab70",
        "#a1bddf",
        "#a3c397",
        "#cad9ed",
        "#ccddc4"
      ]
    },
    {
      "name": "--ds-color-button-primary-fill-fill-hover",
      "kind": "color",
      "values": [
        "#003db4",
        "#2d5124",
        "#002c87",
        "#1f3b1a",
        "#001a4e",
        "#0f2209",
        "#a1bddf",
        "#a3c397",
        "#cad9ed",
        "#ccddc4",
        "#f6faff",
        "#f4fcf1"
      ]
    },
    {
      "name": "--ds-color-button-primary-fill-text",
      "kind": "color",
      "values": [
        "#f8fafc",
        "#fbf9f7",
        "#f8fafc",
        "#fbf9f7",
        "#f8fafc",
        "#fbf9f7",
        "#191d2c",
        "#231d19",
        "#191d2c",
        "#231d19",
        "#080c17",
        "#100c09"
      ]
    },
    {
      "name": "--ds-color-button-primary-fill-text-hover",
      "kind": "color",
      "values": [
        "#f8fafc",
        "#fbf9f7",
        "#f8fafc",
        "#fbf9f7",
        "#f8fafc",
        "#fbf9f7",
        "#191d2c",
        "#231d19",
        "#191d2c",
        "#231d19",
        "#080c17",
        "#100c09"
      ]
    },
    {
      "name": "--ds-color-button-primary-fill-border",
      "kind": "color",
      "values": [
        "#0053d0",
        "#3b672d",
        "#003db4",
        "#2d5124",
        "#002c87",
        "#1f3b1a",
        "#70a3d9",
        "#7fab70",
        "#a1bddf",
        "#a3c397",
        "#cad9ed",
        "#ccddc4"
      ]
    },
    {
      "name": "--ds-color-button-primary-fill-border-hover",
      "kind": "color",
      "values": [
        "#003db4",
        "#2d5124",
        "#002c87",
        "#1f3b1a",
        "#001a4e",
        "#0f2209",
        "#a1bddf",
        "#a3c397",
        "#cad9ed",
        "#ccddc4",
        "#f6faff",
        "#f4fcf1"
      ]
    },
    {
      "name": "--ds-button-primary-fill-border-width",
      "kind": "size",
      "values": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  ],
  "sizeTokens": [
    {
      "name": "--ds-text-body-size-m",
      "kind": "size",
      "values": [
        16,
        19.2,
        22.4,
        25.6,
        28.8,
        32,
        18,
        21.6,
        25.2,
        28.8,
        32.4,
        36,
        18,
        21.6,
        25.2,
        28.8,
        32.4,
        36
      ]
    },
    {
      "name": "--ds-text-body-font-family",
      "kind": "font-family",
      "values": [
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter"
      ]
    },
    {
      "name": "--ds-text-body-weight-default",
      "kind": "number",
      "values": [
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400,
        400
      ]
    },
    {
      "name": "--ds-buttons-large-typography-font-family",
      "kind": "font-family",
      "values": [
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter",
        "Inter"
      ]
    },
    {
      "name": "--ds-buttons-large-typography-font-weight",
      "kind": "number",
      "values": [
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500,
        500
      ]
    },
    {
      "name": "--ds-buttons-large-typography-font-size",
      "kind": "size",
      "values": [
        16,
        19.2,
        22.4,
        25.6,
        28.8,
        32,
        18,
        21.6,
        25.2,
        28.8,
        32.4,
        36,
        18,
        21.6,
        25.2,
        28.8,
        32.4,
        36
      ]
    },
    {
      "name": "--ds-buttons-large-spacing-equal",
      "kind": "size",
      "values": [
        16,
        16,
        16,
        16,
        16,
        16,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18
      ]
    },
    {
      "name": "--ds-buttons-large-spacing-horizontal",
      "kind": "size",
      "values": [
        16,
        16,
        16,
        16,
        16,
        16,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18
      ]
    },
    {
      "name": "--ds-buttons-large-spacing-vertical",
      "kind": "size",
      "values": [
        8,
        8,
        8,
        8,
        8,
        8,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10
      ]
    },
    {
      "name": "--ds-buttons-large-spacing-gap",
      "kind": "size",
      "values": [
        8,
        8,
        8,
        8,
        8,
        8,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10,
        10
      ]
    },
    {
      "name": "--ds-buttons-large-spacing-border-radius",
      "kind": "size",
      "values": [
        12,
        12,
        12,
        12,
        12,
        12,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14,
        14
      ]
    },
    {
      "name": "--ds-buttons-large-spacing-focus-radius",
      "kind": "size",
      "values": [
        16,
        16,
        16,
        16,
        16,
        16,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18
      ]
    },
    {
      "name": "--ds-buttons-large-spacing-icon-size",
      "kind": "size",
      "values": [
        20,
        20,
        20,
        20,
        20,
        20,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24,
        24
      ]
    }
  ],
  "autoScreen": {
    "breakpointPx": 768,
    "whenMobile": [
      {
        "name": "--ds-text-body-size-m",
        "kind": "size",
        "value": 16
      },
      {
        "name": "--ds-text-body-font-family",
        "kind": "font-family",
        "value": "Inter"
      },
      {
        "name": "--ds-text-body-weight-default",
        "kind": "number",
        "value": 400
      },
      {
        "name": "--ds-buttons-large-typography-font-family",
        "kind": "font-family",
        "value": "Inter"
      },
      {
        "name": "--ds-buttons-large-typography-font-weight",
        "kind": "number",
        "value": 500
      },
      {
        "name": "--ds-buttons-large-typography-font-size",
        "kind": "size",
        "value": 16
      },
      {
        "name": "--ds-buttons-large-spacing-equal",
        "kind": "size",
        "value": 16
      },
      {
        "name": "--ds-buttons-large-spacing-horizontal",
        "kind": "size",
        "value": 16
      },
      {
        "name": "--ds-buttons-large-spacing-vertical",
        "kind": "size",
        "value": 8
      },
      {
        "name": "--ds-buttons-large-spacing-gap",
        "kind": "size",
        "value": 8
      },
      {
        "name": "--ds-buttons-large-spacing-border-radius",
        "kind": "size",
        "value": 12
      },
      {
        "name": "--ds-buttons-large-spacing-focus-radius",
        "kind": "size",
        "value": 16
      },
      {
        "name": "--ds-buttons-large-spacing-icon-size",
        "kind": "size",
        "value": 20
      }
    ],
    "whenDesktop": [
      {
        "name": "--ds-text-body-size-m",
        "kind": "size",
        "value": 18
      },
      {
        "name": "--ds-text-body-font-family",
        "kind": "font-family",
        "value": "Inter"
      },
      {
        "name": "--ds-text-body-weight-default",
        "kind": "number",
        "value": 400
      },
      {
        "name": "--ds-buttons-large-typography-font-family",
        "kind": "font-family",
        "value": "Inter"
      },
      {
        "name": "--ds-buttons-large-typography-font-weight",
        "kind": "number",
        "value": 500
      },
      {
        "name": "--ds-buttons-large-typography-font-size",
        "kind": "size",
        "value": 18
      },
      {
        "name": "--ds-buttons-large-spacing-equal",
        "kind": "size",
        "value": 18
      },
      {
        "name": "--ds-buttons-large-spacing-horizontal",
        "kind": "size",
        "value": 18
      },
      {
        "name": "--ds-buttons-large-spacing-vertical",
        "kind": "size",
        "value": 10
      },
      {
        "name": "--ds-buttons-large-spacing-gap",
        "kind": "size",
        "value": 10
      },
      {
        "name": "--ds-buttons-large-spacing-border-radius",
        "kind": "size",
        "value": 14
      },
      {
        "name": "--ds-buttons-large-spacing-focus-radius",
        "kind": "size",
        "value": 18
      },
      {
        "name": "--ds-buttons-large-spacing-icon-size",
        "kind": "size",
        "value": 24
      }
    ]
  }
};
